# Production Docker Compose for WyngAI
version: '3.8'

services:
  wyngai-rag:
    build:
      context: .
      dockerfile: Dockerfile.wyngai
    ports:
      - "8000:8000"
    environment:
      - WYNGAI_POSTGRES_HOST=postgres
      - WYNGAI_POSTGRES_DB=wyngai_prod
      - WYNGAI_POSTGRES_USER=wyngai
      - WYNGAI_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WYNGAI_ENVIRONMENT=production
    volumes:
      - ./warehouse:/workspace/warehouse:ro
      - ./rag/index:/workspace/rag/index:ro
      - ./data:/workspace/data:ro
    depends_on:
      - postgres
    restart: unless-stopped
    command: ["wyngai", "serve-rag", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=wyngai_prod
      - POSTGRES_USER=wyngai
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wyngai-rag
    restart: unless-stopped

volumes:
  postgres_data: