#!/bin/bash

echo "🚀 Wyng Lite - Node.js Upgrade Guide"
echo "===================================="
echo ""
echo "Your current Node.js version is quite old (v12.5.0)."
echo "Wyng Lite requires Node.js 18+ for modern features."
echo ""
echo "📋 Quick Upgrade Steps:"
echo ""
echo "1. Install/Update nvm (Node Version Manager):"
echo "   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
echo ""
echo "2. Restart your terminal or run:"
echo "   source ~/.bashrc"
echo ""
echo "3. Install Node.js 18:"
echo "   nvm install 18"
echo "   nvm use 18"
echo "   nvm alias default 18"
echo ""
echo "4. Verify installation:"
echo "   node --version  # should show v18.x.x"
echo "   npm --version   # should show 9.x.x or higher"
echo ""
echo "5. Then return to Wyng Lite directory and run:"
echo "   cd /Users/ericchiyembekeza/Desktop/Claude"
echo "   rm -rf node_modules package-lock.json"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "🎯 After upgrade, the full Wyng Lite application will work perfectly!"
echo "💡 This will take about 5 minutes and give you access to all features."